// dnf spec — DNF package manager (RHEL/Rocky/Alma/Fedora)
const completionSpec = {
  name: "dnf",
  description: "DNF package manager (RHEL/Rocky/Alma/Fedora)",
  subcommands: [
    { name: "install", description: "Install a package", args: { name: "package", isVariadic: true } },
    { name: "remove", description: "Remove a package", args: { name: "package", isVariadic: true } },
    { name: "upgrade", description: "Upgrade installed packages", args: { name: "package", isOptional: true, isVariadic: true } },
    { name: "update", description: "Alias for upgrade", args: { name: "package", isOptional: true, isVariadic: true } },
    { name: "autoremove", description: "Remove unneeded packages installed as dependencies" },
    { name: "reinstall", description: "Reinstall a package", args: { name: "package", isVariadic: true } },
    { name: "downgrade", description: "Downgrade a package", args: { name: "package", isVariadic: true } },
    { name: "distro-sync", description: "Synchronize installed packages to the latest available versions", args: { name: "package", isOptional: true, isVariadic: true } },
    { name: "swap", description: "Remove one package and install another in a single transaction", args: [
      { name: "remove-spec" },
      { name: "install-spec" },
    ]},
    { name: "search", description: "Search package details for the given string", args: { name: "keyword", isVariadic: true } },
    { name: "info", description: "Display details about a package", args: { name: "package", isVariadic: true } },
    { name: "list", description: "List packages", subcommands: [
      { name: "installed", description: "List installed packages" },
      { name: "available", description: "List available packages" },
      { name: "updates", description: "List packages with updates available" },
      { name: "obsoletes", description: "List obsoleting packages" },
      { name: "all", description: "List all packages" },
    ]},
    { name: "provides", description: "Find which package provides a file/feature", args: { name: "feature" } },
    { name: "clean", description: "Clean cached data", subcommands: [
      { name: "all", description: "Clean all cached data" },
      { name: "packages", description: "Clean cached packages" },
      { name: "metadata", description: "Clean cached metadata" },
      { name: "dbcache", description: "Clean cached db data" },
      { name: "expire-cache", description: "Expire the cache" },
    ]},
    { name: "makecache", description: "Generate the metadata cache" },
    { name: "repolist", description: "Display configured software repositories", subcommands: [
      { name: "all", description: "List all repos" },
      { name: "enabled", description: "List enabled repos" },
      { name: "disabled", description: "List disabled repos" },
    ]},
    { name: "repoinfo", description: "Display repository information" },
    { name: "history", description: "View and manage DNF transaction history", subcommands: [
      { name: "list", description: "List transactions" },
      { name: "info", description: "Show transaction details", args: { name: "id" } },
      { name: "undo", description: "Undo a transaction", args: { name: "id" } },
      { name: "redo", description: "Redo a transaction", args: { name: "id" } },
      { name: "rollback", description: "Rollback to a previous transaction", args: { name: "id" } },
    ]},
    { name: "group", description: "Manage package groups", subcommands: [
      { name: "install", description: "Install a package group", args: { name: "group" } },
      { name: "remove", description: "Remove a package group", args: { name: "group" } },
      { name: "list", description: "List available package groups" },
      { name: "info", description: "Display details about a package group", args: { name: "group" } },
      { name: "upgrade", description: "Upgrade a package group", args: { name: "group", isOptional: true } },
    ]},
    { name: "module", description: "Manage application stream modules", subcommands: [
      { name: "list", description: "List modules", subcommands: [
        { name: "all", description: "List all modules" },
        { name: "enabled", description: "List enabled modules" },
        { name: "disabled", description: "List disabled modules" },
        { name: "installed", description: "List installed modules" },
      ]},
      { name: "info", description: "Show module details", args: { name: "module", isVariadic: true } },
      { name: "install", description: "Install a module profile", args: { name: "module", isVariadic: true } },
      { name: "remove", description: "Remove installed module profiles", args: { name: "module", isVariadic: true } },
      { name: "enable", description: "Enable a module stream", args: { name: "module", isVariadic: true } },
      { name: "disable", description: "Disable a module", args: { name: "module", isVariadic: true } },
      { name: "reset", description: "Reset module state", args: { name: "module", isVariadic: true } },
      { name: "update", description: "Update installed modules", args: { name: "module", isOptional: true, isVariadic: true } },
    ]},
    { name: "check-update", description: "Check for available package upgrades" },
    { name: "check-upgrade", description: "Alias for check-update" },
  ],
  options: [
    { name: "-y", description: "Answer yes to all questions" },
    { name: "-q", description: "Quiet operation" },
    { name: "-v", description: "Verbose operation" },
    { name: "--enablerepo", description: "Enable a repository", args: { name: "repo" } },
    { name: "--disablerepo", description: "Disable a repository", args: { name: "repo" } },
    { name: "--nogpgcheck", description: "Disable GPG signature checking" },
    { name: "--skip-broken", description: "Skip packages with dependency problems" },
    { name: "--showduplicates", description: "Show duplicate packages in repos" },
    { name: "--installroot", description: "Set install root", args: { name: "path", template: "folders" } },
    { name: "-C", description: "Run entirely from system cache" },
    { name: "--security", description: "Include only security-related packages" },
    { name: ["-h", "--help"], description: "Show help" },
  ],
};

export default completionSpec;
